include ../Makefile.com

partI: proofs_intro propositions templates induction number_theory

partII: structures_intro simple_graphs digraphs relations state_machines

partIII: counting_intro asymptotics recurrences counting \
	generating_functions infinity

partIV: probability_intro probability conditional_probability \
	random_variables expectation deviation random_walks

chapters: partI partII partIII partIV
